import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Navbar from "@/components/shared/Navbar";
import Footer from "@/components/shared/Footer";
import MyPlanProvider from "@/context/MyPlanContext";
import { ToastContainer } from "react-toastify";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }: LayoutProps<"/">) {
  return (
    <html
      lang="en"
      className={`${geistSans.variable} ${geistMono.variable} h-full antialiased`}
    >
      <body className="min-h-full flex flex-col bg-[#0c0d10] text-[#ffffff]  ">
        <MyPlanProvider>
          <Navbar></Navbar>
          <hr className="text-slate-700 container mx-auto" />
          {children}
          <hr className="text-slate-700 container mx-auto" />
          <Footer></Footer>
          <ToastContainer />
        </MyPlanProvider>
      </body>
    </html>
  );
}
